name: Vulnerability Scan

on: [push, pull_request]

permissions:
  security-events: write
  contents: read

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v5 # Updated
      - uses: actions/setup-go@v6 # Updated
        with:
          go-version: '1.26'

      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          output-format: sarif
          output-file: results.sarif

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif
